<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>4GL</string>
    <key>scopeName</key>
    <string>source.4gl</string>
    <key>fileTypes</key>
    <array>
      <string>4gl</string>
      <string>4GL</string>
    </array>
    <key>uuid</key>
    <string>8faf6be5-5e96-4a45-bca7-7f0387a04215</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#document-block-comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block-comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#single-line-comment-double-dash</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#single-line-comment-number-sign</string>
          </dict>
        </array>
      </dict>
      <key>document-block-comment</key>
      <dict>
        <key>name</key>
        <string>comment.block.documentation.4gl</string>
        <key>begin</key>
        <string>(\#\+)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.4gl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>^(?!\s*\#\+)</string>
      </dict>
      <key>single-line-comment-double-dash</key>
      <dict>
        <key>name</key>
        <string>comment.line.double-dash.4gl</string>
        <key>begin</key>
        <string>(^[ \t]+)?(--)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.comment.leading.4gl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.4gl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=$)</string>
      </dict>
      <key>single-line-comment-number-sign</key>
      <dict>
        <key>name</key>
        <string>comment.line.number-sign.4gl</string>
        <key>begin</key>
        <string>(^[ \t]+)?(#(?!\+))</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.whitespace.comment.leading.4gl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.4gl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=$)</string>
      </dict>
      <key>block-comment</key>
      <dict>
        <key>name</key>
        <string>comment.block.4gl</string>
        <key>begin</key>
        <string>(\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.4gl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.4gl</string>
          </dict>
        </dict>
      </dict>
    </dict>
  </dict>
</plist>